### ISSUE TITLE
Update logic for placing projects in dashboard sections sections

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#73]
AB#10519

## User Story:
As an applicant team member, I need to see all of my active projects and see which ones I can take action on (i.e. submit a PAS).

## Display Logic:

Wireframes are provided for reference at the bottom of this GitHub issue.

**Project shows up at the top with an "Edit Pre-Application Statement" button if**
- Project
  - [x] `statecode = 'Active'` (filtered server-side. See #64)
  - [x] `dcp_visibility IN ('Applicant Only', 'General Public')` (filtered server-side See #64)
- Project applicant team
  - [x] `statuscode = 'Active'` (filtered server-side. See #64)
- PAS package 
  - [ ] `statuscode = 'Package Preparation'`
  - [x] `dcp_visibility IN ('Applicant Only', 'General Public')` (filtered server-side. See See #64 )
- [ ] Sorted alphabetically by project name

**Project appears in bottom section if**
- Project
  - [x] `statecode = 'Active'` (filtered server-side. See #64)
  - [x] `dcp_visibility IN ('Applicant Only', 'General Public')` (filtered server-side. See #64)
- Project applicant team
  - [x] `statuscode = 'Active'` (filtered server-side. See See #64)
- [ ] Sorted alphabetically by project name

Within the projects listed in the bottom section, display "View Pre-Application Statement" button if
  - [ ] PAS package `statuscode IN ('Submitted', 'Under review', 'Reviewed – No Revisions Required', 'Reviewed – Revisions Required')` all statuses except for 'Mistake'
    - Or, `statuscode NOT IN ('Package Preparation', 'Mistake')`
  - [x] PAS package `dcp_visibility IN ('Applicant Only', 'General Public')` (filtered server-side. See See #64 )

**If user isn't assigned to any projects**
Page should display a message. See wireframes.

## [Figma Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP-Wireframes?node-id=0%3A1)
![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/083eca19-b3bd-4894-a7f7-e4a07d8422d3)

**Comment by trbmcginnis** [comment]
Notes on what was talked about during demo: https://docs.google.com/document/d/17rNCMWqlupVkuxIrT_XCvZYS99z1H5469RzDbPMNPZQ/edit?usp=sharing

**Comment by ksinghprod** [comment]
Hi @hannahkates @godfreyyeung  

for projects that both a PAS package in the -package preparation status and have a Pas Package in in the Reviewed-Revision Required, should it show up at the top and the bottom of the page? 

Currently, Only the package preparation Pas Package is appearing ( at the top of the page), is this as per the design/logic?


![image](https://user-images.githubusercontent.com/57362229/79497772-42588000-7ff6-11ea-886f-cbf95d307726.png)


![image](https://user-images.githubusercontent.com/57362229/79498060-b7c45080-7ff6-11ea-9342-63e71c1a7cf1.png)
